name: Build AutoWiFi IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show project files
        run: |
          find AutoWiFi -maxdepth 3 -type f | sort

      - name: Build iOS App
        run: |
          xcodebuild \
            -project AutoWiFi/AutoWiFi.xcodeproj \
            -scheme AutoWiFi \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PRODUCT_BUNDLE_IDENTIFIER=com.nguyenchayshope7.autowifi

      - name: Check Bundle Identifier
        run: |
          echo "Checking app bundle..."
          /usr/libexec/PlistBuddy \
            -c "Print :CFBundleIdentifier" \
            build/Build/Products/Release-iphoneos/AutoWiFi.app/Info.plist

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/AutoWiFi.app Payload/

          /usr/libexec/PlistBuddy \
            -c "Print :CFBundleIdentifier" \
            Payload/AutoWiFi.app/Info.plist

          zip -r AutoWiFi.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AutoWiFi-IPA
          path: AutoWiFi.ipa
